#!/usr/bin/env python3
"""Tests for tools/auto_merge_ingestion_pr.py (E41f).

Covers:
  - is_path_allowed / first_disallowed_path against the documented allowlist
  - title_matches / branch_matches
  - required_checks_status state machine
  - main() flow under the various skip / block / merge paths
"""

import importlib
import json
import sys
from pathlib import Path

import pytest


@pytest.fixture
def mod():
    # Import lazily so test discovery works even if the file is added later.
    sys.path.insert(0, "tools")
    m = importlib.import_module("auto_merge_ingestion_pr")
    yield m
    importlib.reload(m)


class TestPathAllowlist:
    @pytest.mark.parametrize(
        "path",
        [
            "articles/2026-05-04-x/article.md",
            "articles/2026-05-04-x/metadata.json",
            "articles/2026-05-04-some-long-slug-2026/article.md",
            "README.md",
            "ROADMAP.md",
            "index.json",
            "sitemap.xml",
            "feed.xml",
            "feed.json",
            "llms.txt",
            "llms-full.txt",
            "llms-recent.txt",
            # Bundled MCP archive snapshot — added by the ingest workflow
            # since PR #210 and tracked by the Generated artifacts drift
            # check. Issue #212 was the regression where this path was
            # accepted by the workflow's `add-paths:` but rejected here,
            # blocking the otherwise-valid PR #211.
            "mcp-server/src/generated/archive-data.json",
            # Middle-context corpus index generated by
            # tools/rebuild_local.py::build_llms_index and tracked by the
            # Generated artifacts drift check (PR #218). Auto-merge must
            # accept this path or every fresh cron ingest blocks on it
            # the way PR #211 blocked on archive-data.json before #214.
            "llms-index.txt",
        ],
    )
    def test_allowed(self, mod, path):
        assert mod.is_path_allowed(path) is True

    @pytest.mark.parametrize(
        "path",
        [
            # Article folders may not have nested subdirs.
            "articles/2026-05-04-x/sub/article.md",
            "articles/2026-05-04-x/sub/metadata.json",
            # Article files must be exactly the two canonical files.
            "articles/2026-05-04-x/notes.md",
            "articles/2026-05-04-x/article.md.bak",
            "articles/2026-05-04-x/.metadata.json",
            "articles/2026-05-04-x/extra.json",
            "articles/2026-05-04-x/article.md/",
            # Top-level files with the wrong path or case.
            "Readme.md",
            "ROADMAP.md.bak",
            "tools/ingest_airtable.py",
            "docs/airtable-ingestion.md",
            ".github/workflows/ingest-airtable.yml",
            # Empty / weird inputs.
            "",
            "/",
            "articles//article.md",
            "articles/x\x00x/article.md",
            # Generated artifacts inside subdirs are not allowed.
            "tests/index.json",
            "subdir/sitemap.xml",
        ],
    )
    def test_disallowed(self, mod, path):
        assert mod.is_path_allowed(path) is False

    def test_first_disallowed_path_returns_first_violation(self, mod):
        paths = [
            "articles/2026-05-04-x/article.md",
            "tools/ingest_airtable.py",  # ← violator
            "README.md",
            "docs/something.md",
        ]
        assert mod.first_disallowed_path(paths) == "tools/ingest_airtable.py"

    def test_first_disallowed_path_returns_none_when_clean(self, mod):
        paths = [
            "articles/2026-05-04-x/article.md",
            "articles/2026-05-04-x/metadata.json",
            "README.md",
            "ROADMAP.md",
        ]
        assert mod.first_disallowed_path(paths) is None

    def test_auto_merge_allowlist_matches_ingest_add_paths(self, mod):
        """Regression guard for issue #212.

        PR #210 added `mcp-server/src/generated/archive-data.json` to
        `.github/workflows/ingest-airtable.yml`'s `add-paths:` list and to
        `tools/check_generated_artifacts.py::ARTIFACTS` but forgot to add
        the same path to `tools/auto_merge_ingestion_pr.py::ALLOWED_PATHS`.
        The next scheduled cron after #210 (run 26679487892) consequently
        opened a clean PR #211 but the auto-merge script's path-shape
        check classified the new file as disallowed, filed
        `E41 auto-merge blocked: file '<path>' not in ingestion allowlist`
        as #212, returned 1, and triggered a duplicate
        `E41 cron ingestion incident:` issue (#213).

        This test pins the invariant: every concrete file path the ingest
        workflow can write to the PR (via the peter-evans/
        create-pull-request `add-paths:` list, excluding the `articles/*`
        glob which the auto-merge script handles via prefix+suffix
        matching on `<folder>/article.md` and `<folder>/metadata.json`)
        MUST be accepted by `is_path_allowed`. If a contributor adds a
        new tracked generated artifact to the workflow without also
        registering it in ALLOWED_PATHS, this test fails before the gap
        reaches a cron run.
        """
        yaml = pytest.importorskip("yaml")
        repo_root = Path(__file__).resolve().parents[2]
        wf = yaml.safe_load(
            (repo_root / ".github" / "workflows" / "ingest-airtable.yml").read_text(
                encoding="utf-8"
            )
        )
        steps = wf["jobs"]["ingest"]["steps"]
        pr_steps = [
            s for s in steps
            if "peter-evans/create-pull-request" in (s.get("uses") or "")
        ]
        assert len(pr_steps) == 1, (
            "Expected exactly one peter-evans/create-pull-request step in "
            f"ingest-airtable.yml; found {len(pr_steps)}"
        )
        add_paths_raw = (pr_steps[0].get("with") or {}).get("add-paths") or ""
        raw_lines = [ln.strip() for ln in str(add_paths_raw).splitlines() if ln.strip()]

        # `articles/*` is a glob that expands per-folder; the auto-merge
        # script accepts the two canonical filenames inside any article
        # folder. Verify the glob handling separately, then check every
        # other (concrete) entry.
        assert "articles/*" in raw_lines, (
            "ingest-airtable.yml `add-paths:` must continue to list "
            "`articles/*` so new article folders ship on the PR."
        )
        sample_article_folder = "articles/2026-05-04-sample-slug"
        assert mod.is_path_allowed(f"{sample_article_folder}/article.md") is True
        assert mod.is_path_allowed(f"{sample_article_folder}/metadata.json") is True

        concrete_paths = [p for p in raw_lines if p != "articles/*"]
        for path in concrete_paths:
            assert mod.is_path_allowed(path) is True, (
                f"Path '{path}' is in `add-paths:` for the ingest workflow "
                f"but is NOT accepted by auto_merge_ingestion_pr.py::"
                f"ALLOWED_PATHS. Add the matching entry to ALLOWED_PATHS "
                f"to keep the workflow and the auto-merge allowlist in lockstep "
                f"(see PR #210 + issue #212 for the regression history)."
            )


class TestTitleAndBranch:
    def test_title_must_match_exactly(self, mod):
        assert mod.title_matches("ingest(articles): add articles from Airtable") is True
        assert mod.title_matches("ingest(articles): Add articles from Airtable") is False
        assert mod.title_matches("ingest(article): add articles from Airtable") is False
        assert mod.title_matches("") is False

    def test_branch_prefix_required(self, mod):
        # The cron workflow's exact branch must match.
        assert mod.branch_matches("ingest/airtable-articles") is True

        # E20b dispatch branches (ingest/airtable-record-recXXX) must NOT
        # match — they require human review per record, even though the
        # title-match would also reject them. Defense in depth.
        assert mod.branch_matches("ingest/airtable-record-rec123") is False

        # External (Flow B) and unrelated refs must not match.
        assert mod.branch_matches("ingest/article-fixture") is False
        assert mod.branch_matches("main") is False
        assert mod.branch_matches("") is False


class TestRequiredChecksStatus:
    def _rollup(self, **named):
        """Build a rollup like gh's JSON output. {name: conclusion or None}."""
        return [{"name": k, "conclusion": v} for k, v in named.items()]

    def test_all_success(self, mod):
        rollup = self._rollup(
            check="SUCCESS", e2e="SUCCESS", **{"geo-audit": "SUCCESS"},
            gitleaks="SUCCESS", lychee="SUCCESS", readability="SUCCESS",
            test="SUCCESS", vale="SUCCESS",
        )
        state, _ = mod.required_checks_status(rollup)
        assert state == "complete-success"

    def test_one_failure(self, mod):
        rollup = self._rollup(
            check="SUCCESS", e2e="FAILURE", **{"geo-audit": "SUCCESS"},
            gitleaks="SUCCESS", lychee="SUCCESS", readability="SUCCESS",
            test="SUCCESS", vale="SUCCESS",
        )
        state, detail = mod.required_checks_status(rollup)
        assert state == "complete-failure"
        assert "e2e=FAILURE" in detail

    def test_pending_check(self, mod):
        rollup = self._rollup(
            check="SUCCESS", e2e=None, **{"geo-audit": "SUCCESS"},
            gitleaks="SUCCESS", lychee="SUCCESS", readability="SUCCESS",
            test="SUCCESS", vale="SUCCESS",
        )
        state, detail = mod.required_checks_status(rollup)
        assert state == "pending"
        assert "e2e" in detail

    def test_missing_required_check(self, mod):
        # No `vale` reported at all.
        rollup = [
            {"name": n, "conclusion": "SUCCESS"}
            for n in ("check", "e2e", "geo-audit", "gitleaks", "lychee", "readability", "test")
        ]
        state, detail = mod.required_checks_status(rollup)
        assert state == "missing"
        assert "vale" in detail

    def test_extra_unknown_checks_ignored(self, mod):
        """Optional/extra checks must not block when all required are green."""
        rollup = self._rollup(
            check="SUCCESS", e2e="SUCCESS", **{"geo-audit": "SUCCESS"},
            gitleaks="SUCCESS", lychee="SUCCESS", readability="SUCCESS",
            test="SUCCESS", vale="SUCCESS",
            wayback="FAILURE",  # ignored — not in REQUIRED_CHECKS
        )
        state, _ = mod.required_checks_status(rollup)
        assert state == "complete-success"


class TestMainSkipPaths:
    def test_kill_switch_off_silent_skip(self, mod, monkeypatch, capsys):
        monkeypatch.delenv("AUTO_MERGE_INGESTION_PRS", raising=False)
        rc = mod.main()
        assert rc == 0
        assert "[skip]" in capsys.readouterr().out

    def test_kill_switch_value_zero_silent_skip(self, mod, monkeypatch, capsys):
        monkeypatch.setenv("AUTO_MERGE_INGESTION_PRS", "0")
        rc = mod.main()
        assert rc == 0
        assert "[skip]" in capsys.readouterr().out

    def test_no_open_pr_silent_skip(self, mod, monkeypatch, capsys):
        monkeypatch.setenv("AUTO_MERGE_INGESTION_PRS", "1")
        monkeypatch.setattr(mod, "find_open_pr", lambda *a, **kw: None)
        rc = mod.main()
        assert rc == 0
        out = capsys.readouterr().out
        assert "[skip]" in out
        assert "no open PR" in out


class TestMainBlockPaths:
    def _pr(self, **overrides):
        base = {
            "number": 999,
            "url": "https://github.com/o/r/pull/999",
            "title": "ingest(articles): add articles from Airtable",
            "headRefName": "ingest/airtable-articles",
            "baseRefName": "main",
            "mergeable": "MERGEABLE",
            "mergeStateStatus": "CLEAN",
            "files": [
                {"path": "articles/2026-05-04-x/article.md"},
                {"path": "articles/2026-05-04-x/metadata.json"},
                {"path": "README.md"},
            ],
            "statusCheckRollup": [
                {"name": n, "conclusion": "SUCCESS"}
                for n in (
                    "check", "e2e", "geo-audit", "gitleaks",
                    "lychee", "readability", "test", "vale",
                )
            ],
        }
        base.update(overrides)
        return base

    def test_branch_mismatch_blocks(self, mod, monkeypatch, capsys):
        monkeypatch.setenv("AUTO_MERGE_INGESTION_PRS", "1")
        pr = self._pr(headRefName="feature/something-else")
        monkeypatch.setattr(mod, "find_open_pr", lambda *a, **kw: pr)
        issued = {}
        monkeypatch.setattr(
            mod, "open_incident_issue",
            lambda reason, pr=None, repo=None: issued.setdefault("r", reason),
        )
        rc = mod.main()
        assert rc == 1
        assert "head branch" in issued["r"]
        assert "[block]" in capsys.readouterr().out

    def test_title_mismatch_blocks(self, mod, monkeypatch, capsys):
        monkeypatch.setenv("AUTO_MERGE_INGESTION_PRS", "1")
        pr = self._pr(title="something else entirely")
        monkeypatch.setattr(mod, "find_open_pr", lambda *a, **kw: pr)
        issued = {}
        monkeypatch.setattr(
            mod, "open_incident_issue",
            lambda reason, pr=None, repo=None: issued.setdefault("r", reason),
        )
        rc = mod.main()
        assert rc == 1
        assert "title" in issued["r"]

    def test_disallowed_file_blocks(self, mod, monkeypatch):
        monkeypatch.setenv("AUTO_MERGE_INGESTION_PRS", "1")
        pr = self._pr(files=[
            {"path": "articles/2026-05-04-x/article.md"},
            {"path": "tools/ingest_airtable.py"},  # violator
        ])
        monkeypatch.setattr(mod, "find_open_pr", lambda *a, **kw: pr)
        issued = {}
        monkeypatch.setattr(
            mod, "open_incident_issue",
            lambda reason, pr=None, repo=None: issued.setdefault("r", reason),
        )
        rc = mod.main()
        assert rc == 1
        assert "tools/ingest_airtable.py" in issued["r"]
        assert "allowlist" in issued["r"]

    def test_failed_check_blocks_files_issue_but_does_not_fail_cron(self, mod, monkeypatch):
        """A real CI failure on the freshly-created ingest PR must surface
        as an `E41 auto-merge blocked` issue (so an operator can act on
        it), but must NOT also fail the cron run — otherwise the
        failure-path step in the workflow files a duplicate
        `E41 cron ingestion incident:` issue for the same event. The
        single point of truth is the auto-merge-blocked issue.
        """
        monkeypatch.setenv("AUTO_MERGE_INGESTION_PRS", "1")
        rollup = [
            {"name": n, "conclusion": "SUCCESS"}
            for n in ("check", "geo-audit", "gitleaks", "lychee", "readability", "test", "vale")
        ]
        rollup.append({"name": "e2e", "conclusion": "FAILURE"})
        pr = self._pr(statusCheckRollup=rollup)
        monkeypatch.setattr(mod, "find_open_pr", lambda *a, **kw: pr)
        issued = {}
        monkeypatch.setattr(
            mod, "open_incident_issue",
            lambda reason, pr=None, repo=None: issued.setdefault("r", reason),
        )
        rc = mod.main()
        assert rc == 0, (
            "complete-failure must exit 0 so the cron's success-path "
            "incident-cleanup step can sweep stale incidents from prior "
            "failed runs without double-filing for this event."
        )
        assert "CI failed" in issued["r"]
        assert "e2e=FAILURE" in issued["r"]


class TestMainHappyPath:
    def test_clean_pr_is_squash_merged(self, mod, monkeypatch, capsys):
        monkeypatch.setenv("AUTO_MERGE_INGESTION_PRS", "1")
        pr = {
            "number": 165,
            "url": "https://github.com/o/r/pull/165",
            "title": "ingest(articles): add articles from Airtable",
            "headRefName": "ingest/airtable-articles",
            "baseRefName": "main",
            "mergeable": "MERGEABLE",
            "mergeStateStatus": "CLEAN",
            "files": [
                {"path": "articles/2026-05-04-x/article.md"},
                {"path": "articles/2026-05-04-x/metadata.json"},
                {"path": "README.md"},
                {"path": "ROADMAP.md"},
                {"path": "index.json"},
                {"path": "sitemap.xml"},
                {"path": "feed.xml"},
                {"path": "feed.json"},
                {"path": "llms.txt"},
                {"path": "llms-full.txt"},
                {"path": "llms-recent.txt"},
            ],
            "statusCheckRollup": [
                {"name": n, "conclusion": "SUCCESS"}
                for n in ("check", "e2e", "geo-audit", "gitleaks",
                         "lychee", "readability", "test", "vale")
            ],
        }
        monkeypatch.setattr(mod, "find_open_pr", lambda *a, **kw: pr)
        merged = {}
        monkeypatch.setattr(mod, "squash_merge",
                            lambda n, repo=None: merged.setdefault("n", n))
        rc = mod.main()
        assert rc == 0
        assert merged["n"] == 165
        out = capsys.readouterr().out
        assert "[merge]" in out
        assert "[done]" in out

    def test_pending_then_success_polls_until_green(self, mod, monkeypatch):
        monkeypatch.setenv("AUTO_MERGE_INGESTION_PRS", "1")
        monkeypatch.setenv("AUTO_MERGE_TIMEOUT_SECONDS", "5")
        monkeypatch.setenv("AUTO_MERGE_POLL_INTERVAL", "0")  # don't actually wait

        pr_pending = {
            "number": 200,
            "url": "https://github.com/o/r/pull/200",
            "title": "ingest(articles): add articles from Airtable",
            "headRefName": "ingest/airtable-articles",
            "baseRefName": "main",
            "mergeable": "MERGEABLE",
            "mergeStateStatus": "BLOCKED",
            "files": [{"path": "README.md"}],
            "statusCheckRollup": [
                {"name": "check", "conclusion": "SUCCESS"},
                {"name": "e2e", "conclusion": None},  # pending
                {"name": "geo-audit", "conclusion": "SUCCESS"},
                {"name": "gitleaks", "conclusion": "SUCCESS"},
                {"name": "lychee", "conclusion": "SUCCESS"},
                {"name": "readability", "conclusion": "SUCCESS"},
                {"name": "test", "conclusion": "SUCCESS"},
                {"name": "vale", "conclusion": "SUCCESS"},
            ],
        }
        pr_done = dict(pr_pending)
        pr_done["mergeStateStatus"] = "CLEAN"
        pr_done["statusCheckRollup"] = [
            {"name": n, "conclusion": "SUCCESS"}
            for n in ("check", "e2e", "geo-audit", "gitleaks",
                     "lychee", "readability", "test", "vale")
        ]

        responses = iter([pr_pending, pr_done])
        monkeypatch.setattr(mod, "find_open_pr",
                            lambda *a, **kw: next(responses))
        merged = {}
        monkeypatch.setattr(mod, "squash_merge",
                            lambda n, repo=None: merged.setdefault("n", n))
        # Avoid real sleep.
        monkeypatch.setattr(mod.time, "sleep", lambda _s: None)
        rc = mod.main()
        assert rc == 0
        assert merged["n"] == 200

    def test_timeout_blocks_with_incident(self, mod, monkeypatch):
        monkeypatch.setenv("AUTO_MERGE_INGESTION_PRS", "1")
        monkeypatch.setenv("AUTO_MERGE_TIMEOUT_SECONDS", "0")  # immediate timeout
        monkeypatch.setenv("AUTO_MERGE_POLL_INTERVAL", "0")

        pr_pending = {
            "number": 300,
            "url": "https://github.com/o/r/pull/300",
            "title": "ingest(articles): add articles from Airtable",
            "headRefName": "ingest/airtable-articles",
            "mergeable": "MERGEABLE",
            "mergeStateStatus": "BLOCKED",
            "files": [{"path": "README.md"}],
            "statusCheckRollup": [
                {"name": "check", "conclusion": None},
                {"name": "e2e", "conclusion": None},
                {"name": "geo-audit", "conclusion": None},
                {"name": "gitleaks", "conclusion": None},
                {"name": "lychee", "conclusion": None},
                {"name": "readability", "conclusion": None},
                {"name": "test", "conclusion": None},
                {"name": "vale", "conclusion": None},
            ],
        }
        monkeypatch.setattr(mod, "find_open_pr", lambda *a, **kw: pr_pending)
        issued = {}
        monkeypatch.setattr(
            mod, "open_incident_issue",
            lambda reason, pr=None, repo=None: issued.setdefault("r", reason),
        )
        rc = mod.main()
        assert rc == 0, (
            "Polling timeout (required checks not finished yet) must exit 0 "
            "so the cron does not fail merely because a freshly opened PR's "
            "checks have not completed within the auto-merge poll window. "
            "The `E41 auto-merge blocked` issue captures the operator-review "
            "signal; the cron itself stays in success()."
        )
        assert "timed out" in issued["r"]


class TestMergeStateGate:
    """F2: the merge must gate on mergeStateStatus == CLEAN, not just mergeable.

    Regression for run 29186004190 / PR #328: the required checks flipped
    SUCCESS while mergeStateStatus was still BLOCKED (GitHub recomputes it
    asynchronously); the merge attempt then failed with "base branch policy
    prohibits the merge" and double-filed incidents.
    """

    def _pr(self, merge_state, **overrides):
        pr = {
            "number": 328,
            "url": "https://github.com/o/r/pull/328",
            "title": "ingest(articles): add articles from Airtable",
            "headRefName": "ingest/airtable-articles",
            "baseRefName": "main",
            "mergeable": "MERGEABLE",
            "mergeStateStatus": merge_state,
            "files": [{"path": "README.md"}],
            "statusCheckRollup": [
                {"name": n, "conclusion": "SUCCESS"}
                for n in ("check", "e2e", "geo-audit", "gitleaks",
                          "lychee", "readability", "test", "vale")
            ],
        }
        pr.update(overrides)
        return pr

    def test_green_but_blocked_waits_until_clean_then_merges(self, mod, monkeypatch, capsys):
        monkeypatch.setenv("AUTO_MERGE_INGESTION_PRS", "1")
        monkeypatch.setenv("AUTO_MERGE_TIMEOUT_SECONDS", "5")
        monkeypatch.setenv("AUTO_MERGE_POLL_INTERVAL", "0")
        responses = iter([self._pr("BLOCKED"), self._pr("CLEAN")])
        calls = {"n": 0}

        def _find(*a, **kw):
            calls["n"] += 1
            return next(responses)

        monkeypatch.setattr(mod, "find_open_pr", _find)
        merged = {}
        monkeypatch.setattr(mod, "squash_merge", lambda n, repo=None: merged.setdefault("n", n))
        monkeypatch.setattr(mod.time, "sleep", lambda _s: None)
        rc = mod.main()
        assert rc == 0
        assert merged.get("n") == 328, "must merge only after mergeStateStatus becomes CLEAN"
        assert calls["n"] >= 2, "must poll past the BLOCKED state, not merge on the first green poll"
        assert "awaiting CLEAN" in capsys.readouterr().out

    def test_green_but_permanently_blocked_times_out_without_merge(self, mod, monkeypatch):
        monkeypatch.setenv("AUTO_MERGE_INGESTION_PRS", "1")
        monkeypatch.setenv("AUTO_MERGE_TIMEOUT_SECONDS", "0")  # immediate timeout
        monkeypatch.setenv("AUTO_MERGE_POLL_INTERVAL", "0")
        monkeypatch.setattr(mod, "find_open_pr", lambda *a, **kw: self._pr("BLOCKED"))
        merged = {}
        monkeypatch.setattr(mod, "squash_merge", lambda n, repo=None: merged.setdefault("n", n))
        issued = {}
        monkeypatch.setattr(
            mod, "open_incident_issue",
            lambda reason, pr=None, repo=None: issued.setdefault("r", reason),
        )
        rc = mod.main()
        assert rc == 0
        assert "n" not in merged, "must not attempt a merge while mergeStateStatus is BLOCKED"
        assert "timed out" in issued["r"]


class TestMergeRejectionAndDedup:
    def _clean_pr(self, num=328):
        return {
            "number": num,
            "url": f"https://github.com/o/r/pull/{num}",
            "title": "ingest(articles): add articles from Airtable",
            "headRefName": "ingest/airtable-articles",
            "baseRefName": "main",
            "mergeable": "MERGEABLE",
            "mergeStateStatus": "CLEAN",
            "files": [{"path": "README.md"}],
            "statusCheckRollup": [
                {"name": n, "conclusion": "SUCCESS"}
                for n in ("check", "e2e", "geo-audit", "gitleaks",
                          "lychee", "readability", "test", "vale")
            ],
        }

    def test_merge_rejection_returns_zero_and_files_issue(self, mod, monkeypatch):
        """F3a: a squash_merge GhError files the blocked issue and returns 0
        (not 1), so the cron does not fail and double-file a cron incident."""
        monkeypatch.setenv("AUTO_MERGE_INGESTION_PRS", "1")
        monkeypatch.setattr(mod, "find_open_pr", lambda *a, **kw: self._clean_pr())

        def _boom(n, repo=None):
            raise mod.GhError(
                "gh pr merge 328 --squash --delete-branch exited 1: "
                "base branch policy prohibits the merge"
            )

        monkeypatch.setattr(mod, "squash_merge", _boom)
        issued = {}
        monkeypatch.setattr(
            mod, "open_incident_issue",
            lambda reason, pr=None, repo=None: issued.setdefault("r", reason),
        )
        rc = mod.main()
        assert rc == 0
        assert "gh pr merge failed" in issued["r"]

    def test_incident_deduped_when_open_issue_exists(self, mod, monkeypatch, capsys):
        """F3b: open_incident_issue skips creation when an open blocked issue
        already references the PR number."""
        gh_calls = []

        def _fake_gh(args, repo=None):
            gh_calls.append(args)
            if args[:2] == ["issue", "list"]:
                return json.dumps([{"number": 329, "body": "- **PR number:** 328\n"}])
            return ""

        monkeypatch.setattr(mod, "_run_gh", _fake_gh)
        mod.open_incident_issue("some reason", pr={"number": 328, "url": "u"}, repo="o/r")
        assert not any(a[:2] == ["issue", "create"] for a in gh_calls), (
            "must not create a new issue when an open one already tracks the PR"
        )
        assert "[skip]" in capsys.readouterr().out

    def test_incident_created_when_no_existing_issue(self, mod, monkeypatch):
        gh_calls = []

        def _fake_gh(args, repo=None):
            gh_calls.append(args)
            if args[:2] == ["issue", "list"]:
                return json.dumps([])  # none existing
            return ""

        monkeypatch.setattr(mod, "_run_gh", _fake_gh)
        mod.open_incident_issue("some reason", pr={"number": 999, "url": "u"}, repo="o/r")
        assert any(a[:2] == ["issue", "create"] for a in gh_calls), (
            "must create an issue when none exists for the PR"
        )
